apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-apps
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi