apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.9.0/deploy/longhorn.yaml
  - ingress.yml

patches:
  - target:
      kind: Service
      name: longhorn-frontend
      namespace: longhorn-system
    path: service-patch.yml