apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-wal
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1Gi