kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
      component: postgres
  template:
    metadata:
      labels:
        app: lldap
        component: postgres
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database
            # According to the image documentation, PGDATA must be a subdirectory of /var/lib/postgresql/data
            # on filesystems that can't be chowned to the postgres user (e.g. NFS)
            # See: https://hub.docker.com/_/postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_WALDIR
              value: /var/lib/postgresql/wal
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: wal
              mountPath: /var/lib/postgresql/wal
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: wal
          persistentVolumeClaim:
            claimName: postgres-wal