apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi