apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.30.0/controller.yaml
  - ingress.yml

patches:
  - target:
      kind: Service
      name: sealed-secrets-controller
    path: service-controller-patch.yml
  - target:
      kind: Service
      name: sealed-secrets-controller-metrics
    path: service-metrics-patch.yml