apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
labels:
  - pairs:
      app: sealed-secrets
    includeSelectors: true
    includeTemplates: true
resources:
  - namespace.yml
  - service-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - crd-sealed-secret.yml
  - deployment.yml
  - service.yml
  - ingress.yml