apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
  annotations:
    prometheus.starsystem.dev/scrape: "true"
    prometheus.starsystem.dev/scheme: http
    prometheus.starsystem.dev/path: /metrics
    prometheus.starsystem.dev/port: "8081"
    metallb.io/loadBalancerIPs: 10.1.16.2
spec:
  type: LoadBalancer
  ports:
    - name: cert
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081