apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /metrics
    prometheus.io/port: "8081"