apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/stakater/Reloader/refs/heads/master/deployments/kubernetes/kustomization.yaml