apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi