apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-backup
  namespace: redis-cluster
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi