apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.61.0
          args:
            - --is-cluster
          env:
            - name: REDIS_EXPORTER_REDIS_ONLY_METRICS
              value: "true"
            - name: REDIS_ADDR
              value: redis://redis.redis-cluster:6379
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: redis-exporter-credentials
                  key: username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-exporter-credentials
                  key: password
          ports:
            - name: metrics
              containerPort: 9121