---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis-cluster
spec:
  encryptedData:
    users.conf: AgBJXzSJfJn9l5zhQVltW+dzOIc7Bn96ZscyevkHf/ZTDoLyVy/qhnD8NaMmqUcDDc5saaXwhYNQvnp3/YeNUu8FBlt+6X0CVrdIIZLmOjzsyplKdmP0SmaCTYkXrSDbuJaop0YiLtjAn1aHORKSD7HKTWZ3ZP9uZz8p5QxkVl95kg+zOeX3zJcYa9yaS0MCJfAleVRSQCJcBz/SwJEmq0hn29cOkClea3GFG3xA1M/FugewRBjnpqzaxPzyLJ2USmXntoEaBN7l9VUjjMePEvG2tMv/9S/nH5kJs+/Syc96Ij9az8xY6Ybj2hhLtrRvIGCKaR5Cpi/PKvgqu/Bo/akYV1iCKPDS3F51JyysFNY0cWk9yeaK6wuUtcmY9E0BEj2YHaygo3dvqaqeaTDWLegxPVzeeaTLWFt5lHfpz5XHXJC0t4mrkQpa9PFvkuZEWDNEI7wgwX9xcga9KdQ0H1Jr40sQi1EHNUjjgmJKRhDTlEeM86R4fHHIRrFwMcEkTyF8t2tmFn1375ipBjkcTnKHv12uhftAIiy3RLsIqqGJAE2XzSmggJG4WmZs564W9e+sEwqd6iDKSkK7j2NEKYuIp4nUtuuVafzvOS/GqgwombiG5OFl6wF3yZtuM1/1BgYnDTefZz5nccnxoFqL08QSnfkbceTzJRVfaDcYUPupNtxobyq2GhAQVzSvCHSMPMe91rSnm9uRRFZLCU8YBKKtZUtZVU7LjkeIhABTX47ORjhaDUYwhR1bfc9f/q4JQD2TTzZOEoDuEehP/VBu5OSi5sPibe+xgE4pIZMVonkrEI2tLlAJRfx++4XCB4yueM6k8ZcC8xGJAGSCeV02olt/07nVLevOyabNq5wKn0Hzxtp7FxKT8y2GGNUdALtRQG11hviD2PBTtij2xmweCnNJ2WntIFMOI/Rvp5bIR72fvpDt9e2mUvMYINgPUj2MYAzZaiMLrndEfNU6fTCWZU/xDx1LMBbpiaboADlBu7J03Vnun+jBooiGhnabTgCrAb37G84XaZwtNEm5tyH4QEWg17cFPLYyF3U7LvS/+Imk180DaXa8a/QcJss+QdWBqhgVTW0JHo/3ESjqPMV94uzWaBLzYqV814vqkil7AeKJB7QRiSIdUxWi43kFqSyqYHIug25X5Zm5WGheUnn5Wh1+y46/E+N0J3mCpL5Nv6tnxdaSmWZs8K8uofiuQgGnnM2IQACmI2HJiUTS1/5YxkqfSErEa2O1QS409wlRZw4JZ23dCSyJXmOE+3pkLMqF1G4WfkYft+sY71Bxuglc3txHnKZvrpfBywfDmLH+sv6WuKEbgwUFLG+cR4lXWVON4CbhFpsOY/5fPyrSS3sf2nAU3Q3m/+ENDYpc00tzw6/FoGwmHdunC8bY/dNQUMkaFfOScWbclS1QsJJUuES/J3CvyZezDoAo6xMWl6fqrorzW4UQoSGnsnlznNDOxtcMdrgUzhbfTSTUXFFlcDJaMIGHLpIiyl67twLlSNPXy49aKeQBE+ueQLsQbNWzs9wnKBqMhxuEipoW3XQ=
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis-cluster
