---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis-cluster
spec:
  encryptedData:
    users.conf: AgBJzbZtnzc/MiRTGH1Apvrx6N2ZVBLNFCNJEInZOZ3hM4wzQ20UQ5Vgq4dwF+y0NlgotFuPF3vH2eAzgv91XXpP+Snf3ObpLBwxn4P9soh6EMoH2t51PPeFTULZHhvV5YIUC6OlIHI+IyyvoFc7J8svUjzpLo0vSFlJBmPG04sWDOo+cvCZ6CLL8+RSYnnig7j2JezvCVHmkdMxKcvBysksmK2eFciWxf0hqV4QShipnlzj7fyaUoRjI0qTHjWqZ08jig9J7lpScDuaTNim9ysLxTTEO4AqDQMP3v6GFTMZ03l1xfY1zsJv7UJ+h9W0hBLPS/PhX+36DO6zr7jDfszc2VDxK0KSI01GyYKe8Yw57B4oMCZySIdeCAAzWkZ2QPEx28qWMVpA9H3nPf5c2736Rs2BMP9h9pZR8NDQtt8gwN5LCr/rTVXvJEAt8U33MJaDAlgRoLENHCIeI/QjnRyfb7rcEKwICismv38Db4h3ax8FlNGpOSN3f+t33yIqVzquif43k8sOvO37+5jM5glTqLFU9HeI0aJ0F9DSR0Mnm6rzvBGrAh1e3mSEY10YU+bSE1adph703xpkfHN/7ylurqfymMx9QHSnNdyEQ8WPBiQB5t88ARK2VAYGvw5jx94c4247Er7hbmhbqcDWT7e8FZ6BWCvgqvw7GzLTgKtxWVxyZeXiTPiPij+BS3qqCm6LOdtD5sNeKZIWD/voDE4KAX2K53bQoGMeS6hSfeDjpaYBjkT99etGqPseYResRoF/bueIzLeM/W8AQyomnWh63EjGmvoLB/DppX1mktgd81PXEL4fg30cz8bRN3JJZZI0eabl9NtsDtb6UPsHu4RHsjh7xgcEliGD3lgNO8/0mZsZ7iKLuARqYx1OSvz1B0aPC3pcdQo0+FmBIpNxyve2o2otxoUt5EiqPtYLNsRZPZNja/pnVfPvQj14I9pMMAlSeDPUYL8UvQKpZZngBOB/hL0q7N0Fk2egjqx5MDcSjPclBcnd/ljHFw2KLVOs4fxpdoYyKDSgTyh3NpHlKZlS7UYZjliQ+krIbzdF+yTrE2jkNm/MdV5XuvaKy+TmJbmrltOK3SrE5O9qt1lPmM3kCgOHsbyGP5UwGPt84PmeFlX6reLKh+r9l8Q7rxf28iwo14MkyW+3zZudblQnWtRBUtrfR601id/hwUN1jZ32JmCzrI8Gg49MmaM583Q+LzKRwlOs5vRPBBQW0qXZNmUdIB/hdLbPOWUBm+g/Lx5yjvGuf5BB0WSSfqTN5r7CAuQZBnnMvJVVb6R8fmLSljc9XDnFG3L49ZuMskeuMWvY1kOLOgMMB2m2MVJIEZ1MKBXUccKZkXbXPJDFpHAGq0CAN7KZriDSWbGv27lTbr+FLnIt20Kh0/oQVsc5wSdYLjxNcubvoXPNXz+nr3s3hOZRlkqu9ANVqDvgvZsFVUo=
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis-cluster
