apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
  annotations:
    configmap.reloader.stakater.com/reload: "redis-config"
    secret.reloader.stakater.com/reload: "redis-credentials"
spec:
  replicas: 6
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        podAntiAffinity:
          # Since we only have 5 k8s nodes but 6 redis nodes, we need to use preferred instead of required here
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: redis
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis
          image: redis:7.2
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis
            - name: acls
              mountPath: /usr/local/etc/acl
      volumes:
        - name: acls
          secret:
            secretName: redis-credentials
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi