---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis-cluster
spec:
  encryptedData:
    users.conf: AgBfCSXgZlWlmaMjHG8BXcyFQl7f8dSy4qs+fgsGXI/MSfu5TLRZU+YwgcRolVfnmmbIt+yP/1i31kXTpub+vy0JLXXrlAnxOHxWTAu9uHnOvLMlWp8s9SV7I9kEtwOvqqJ/pW7UiPXUg9lGuIPiGz56KK8WcPgxBob3721C3h6QHWKRUXKoFXbGl4oY/aZSySebnZgJxWYPLyuKjnvkmZwVJoyiunNoYAXi/oNhu5OebtXBPDXvbNu3wSBtrl2buZeLb5dypcriiNbRXhr6RoT4HD3SoZJ63y4vC3Tk6tw2+HDZbkzBkJiu5o6IU8fAZnfZdwAlf+CNtGjIFAllsDUXdMAJC8Hq2SYPIQtrUwagbw3hatcKgV03dTlIgYPsZRwJxvgclY9mk0boSw+YxjdiZcGcVMVsJUlGEhyBzfcAj4KA1kMumDJG/MfX+gQcOKYLosvl49Azs/u0Tb5G1MICBMEKs7FQbo+YtOOyeoavSE+A796u0euyAHOgsfywjs1mBt0/dXtZ8t2KQ9WG/dL/lqDazdr6nQRcRzYdgMxCcMP7Qgb1HSmi/LhRDTADuNlUYdnvI7tv8S0OJ1BQHS+EP1hzYYWbN+uIs1J4R8ShO4K5r58ZXpotGQcTVClYGo2dYwajMyynTOB6qNd5cuaBYZaCcSFFagOTMbHWZcTvSS2JlAIGknQcZGwn3Zh21PlLAZaKwfz9u0LmkNg6xNOhNgg9gpVqkc1T7uNwnMUdlf9WafuY83tWAkWAFhYgtMhJkVSFhI6P39zK9B26cLVCi9C+ysGHR+qLennCIoXSQokwrkwE3MfDV4KzyN29CgEB2o3bQNctk4o5gUNoEu84Z3L2rRC8HLlPd0wK7qSGVBH+DJYzInk+naPaXDHXbzh+mKavFjVLH/sAlm6Jb3lwAl2XCqwI8ObQwVa1TsnuhJeiVzW+731eU3o7TKdbNE91lPp+z3xeWpbPaN/mAYx81a2m6CoaerRMnmJe+a9fjSwRTxx7lYZhEpgv/AI5jIGO6142EhU4Uy4SyZWq5+EEaHWNcNer9ODWMectWCyEESeyLubWLz8sC6X03D6mst5qM3ZiMgVYYwIgxa3j/DxXHd3E1nA65mogTOI5D1w7g+ul9f2Bpa1LR2JTe1oHzhCvIoUakIXH/jmBUu58CDTQgxOwhudKIw12rQIdltUiDNPmHuvame6ZxJ1wMyc5OGXy+im5ZpyEBXj2WKXWequJ4Vf+cmGS7uMqkd2qB8iZZsLZCSOxI/e+5/puPTiR9O08mQziTZFzsafq66LX
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis-cluster
