---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis-cluster
spec:
  encryptedData:
    users.conf: AgBANgKGfOsIXaDHSvzT/YvshKTi0lNa/kAjpGh3PEM6/8qwXDS0f+13B/oKoOM82KR33L3p8Z6qT4zaNYT5q2xzcEAHY8nPHnJADA+u92nOMv0i9nzzX9niHmO0sjwGPiziBcOnI5/wE7vNvAkC8DpnmbuEa6Hr/0NJXltrLzyH/3UwTtqr86vZbqQ6pIl1MYflPiboCfJ5G17d5El17AfJyxkgM3x61QG7b6Hj3AngF5aeUBBMetK25FcT599I2RFBMmR/ke+rb6fkiJVaMUNw6kKLa0kKQpY42OXtdKViy8UOENCAWvS1KeauWy3AHqkX8nxh7mVeht8HaO+9jzYJxsEG2vB9LjzaWruzwnPKiFcSH3RekYCiewB4KjuqMjqQ1Pkfl1g1+UEVehh97hIyXSMDbzYiGaXOIAAED96CkEPW3svDg1lPLWy6EDqoQs9LFcp4B7voaP8VMWUdIy7xwfCeAaJa5ckaTDBNrgBXZm7KIFXtPBgorcnXWzVJku1oDGgxr5Xaj06HXmnpt2H0/4SdLyUn4ylCGEtJkiksoxpgoDW+jApW3LwsgNfgp7ENkD72OWcobhApkhHc7oB4l72MS4bdz+LYJwUkS/dLjTdeJrMfyoohtoGn8xMNBw/gjyi15gxIS6+qgFXJqw/pAdmrPsNRRzmFmbxIAw1PGVLXHSicL0+E1pKM4vXziC2iRAX4WnubUSmPQ9kgwdLisKPJvcTMvZYbCuzH1PYpMXe6eRm7uJpXlCaFNYCjAXBBiJ8vgXNB3mvY9KLOQfD2vVuFLfLIYYxwN5QLMXRgGyMQ5UuXcmLSX1S1gt/cv/IV8sGuOt88nwk3FACv1A8bf1nyqcMPlmkQJuMvs8tlHxXi8MmqBADxwaqwlicoFSIS1wDcpMKyrauuoL5CSqOUq/Mn+/kebu1uMEGdUh6i47+n0sKIkdbCcPt66AcA9tdXxK0AWqL3qWk8vMd4NGb4wgWd5pBip70euODrUfs92aRyeYfq3YOrpsAcQsmYcuZMfQ57e8vEiTXoFbXkVR/53jmD1Z2qYfj91XemStSEbLILm8UFS+5h5wkCroimN5sbqyn+Uy7PH3Gph6HhfYwJpt/bDO2WA+ITJj6JoZ9xjTvY9Nr6FUntdgnAybJ/o5Y2TctXm2KHXKse+k54hiICTIiqbV9pBPIwC9W4n+CkK0Ak/U9hgh3emZj+7OYqJWToUNijwvMe1JGzhMvSD9rGtFqMFebB0MvHwFy0UhAxCbjF+02OdjbSr2VOeG6j/TCMiYPSv/eJFmYEbzwi+SP35PF2YiIezCB4VuvyVpOt47mHP7VAjrTqjQ7I3A6iDvMCgCo1ImDDgg+SpwTeOvVNKvaJpHEydOiiUk+2mk+Ek/vh5OS7uaWsW4Mnre4kN3Znotz65GVeYBm+dg==
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis-cluster
