apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
labels:
  - pairs:
      app: traefik
    includeSelectors: true
    includeTemplates: true
resources:
  - namespace.yml
  - service-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - crd-middleware.yml
  - middleware-cors.yml
  - daemonset.yml
  - service-dashboard.yml
  - service-proxy.yml
  - ingress-dashboard.yml