apiVersion: v1
kind: Service
metadata:
  name: sagittarius
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.3.0.1
  ports:
    - name: truenas
      port: 80
      targetPort: 80
    - name: immich
      port: 2283
      targetPort: 2283
    - name: portainer
      port: 9000
      targetPort: 9000
    - name: opencloud
      port: 9200
      targetPort: 9200
    - name: wopi
      port: 9300
      targetPort: 9300
    - name: collabora
      port: 9980
      targetPort: 9980