apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml

patches:
  - target:
      kind: Service
      name: argocd-server
      namespace: argocd
    path: service-patch.yml