apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml

patches:
  - target:
      kind: Service
      name: argocd-server
      namespace: argocd
    path: service-patch.yml
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server
      namespace: argocd