apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-wal
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1Gi