apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-data
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi