apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  description: "PostgreSQL server for Authentik"
  priorityClassName: system-cluster-critical
  instances: 3
  storage:
    storageClass: nfs
    size: 5Gi
  # WAL works better on local storage than NFS
  # Having it separate from Sagittarius also helps recovery if Sagittarius goes down suddenly
  # WALs are semi-ephemeral so there's no need to worry about backups or persistence across nodes
  walStorage:
    storageClass: local
    size: 1Gi