apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - photos.starsystem.dev
      secretName: immich-tls
  rules:
    - host: photos.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sagittarius
                port:
                  number: 2283