apiVersion: v1
kind: Service
metadata:
  name: sagittarius
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.3.0.1
  ports:
    - name: truenas
      port: 80
      targetPort: 80
    - name: portainer
      port: 9000
      targetPort: 9000

    - name: immich
      port: 2283
      targetPort: 2283

    - name: jellyfin
      port: 8096
      targetPort: 8096
    - name: jellystat
      port: 3000
      targetPort: 3000
    - name: jellyseerr
      port: 5055
      targetPort: 5055

    - name: fileflows
      port: 5000
      targetPort: 5000

    - name: qui
      port: 7476
      targetPort: 7476
    - name: qui-metrics
      port: 9074
      targetPort: 9074
    - name: qbittorrent
      port: 8080
      targetPort: 8080

    - name: bazarr
      port: 6767
      targetPort: 6767
    - name: tdarr
      port: 8265
      targetPort: 8265
    - name: prowlarr
      port: 9696
      targetPort: 9696
    - name: radarr
      port: 7878
      targetPort: 7878
    - name: sonarr
      port: 8989
      targetPort: 8989
    - name: lidarr
      port: 8686
      targetPort: 8686
    - name: unpackerr # Note: metrics only
      port: 5656
      targetPort: 5656
    - name: cleanuparr
      port: 11011
      targetPort: 11011
    - name: autobrr
      port: 7474
      targetPort: 7474
    - name: autobrr-metrics
      port: 7575
      targetPort: 7575

    - name: opencloud
      port: 9200
      targetPort: 9200
    - name: wopi
      port: 9300
      targetPort: 9300
    - name: collabora
      port: 9980
      targetPort: 9980