apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  annotations:
    metallb.io/loadBalancerIPs: 10.1.16.5
spec:
  selector:
    app: adguard
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP