apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - sync
  - hard
parameters:
  server: sagittarius.starsystem.dev
  share: /mnt/storage-pool/hydra
  mountPermissions: "0777"
  onDelete: delete