apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: admin@starsystem.dev
    profile: tlsserver # See https://letsencrypt.org/docs/profiles/#tlsserver
    # In development environments, use https://acme-staging-v02.api.letsencrypt.org/directory instead
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: acme-dns
              key: cloudflare-key