apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
labels:
  - pairs:
      app: cert-manager
    includeSelectors: true
    includeTemplates: true
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.0/cert-manager.yaml
  - sealed.secret-acme-dns.yml
  - cluster-issuer.yml