---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials-authelia
  namespace: postgresql-cluster
spec:
  encryptedData:
    password: AgBveAnX+5Fa1PksxsdNmc0jDjRyzZI1gzVtzhSexOOPa2CemxtmkXIgfbD4mk+Y1SEQ/vlnSM3QBjACcBQpXxurA8jdpm1rh2CM5pjokFpoQswh7wXHotR/jtKcEXNM7uJ3sCDPoJTU99P/ABZnslu81OUkkAcuQnAJFKSWD58AvGFbY1E6wMm6TjyZ8maUu+vZM5DYHLjbR/go1StaFG4QM5/90sjHaZ48cjXMzq6wpf61tXbPMDTpo3YBvVtGNe68Ks6Iwo2JfZkj9iz7XaZ8AqEdfXPqQ7k/u0Ku4WlbCU6/LiufFnRByMz47RzkAiSpGWJ4mkI1JEIXYdMi77AZqrGAlqSH2fwZoeYd0ZlJ/27KZ8R6v9ejazYxyEApha4h3FH6yhI/GHhIyL3/mNK/crDyL4QpunXyEc2HUy4m5ggihzXXBxvbhlHt6QXtTmHMDP0/YcWG0VBkfXo5uc8UBPZzIEOlgpxohRHw9xppsJBpi6YCFlVlY1aPSl5D99jSd85ipY0EIN/ZhKQRdaCxblF2N9BW2BgGP8+lKUFi0E07wuAi82OXnoC4rvd3OryCMXBVoMWJKs9FyloLr1YBmlCr2nIyBcSfNGIrxSZ2c/uotAtVEXNb9SzKu3Ta3sdqrPzWRHMr1+A2fah9/BpSQDgQ609/BpZwAEV8TlVadNARl48tCOTO3euYPj61R4/Oj4CwGdAZRd7zwo75LnHNeOENjzid+0GfpC6BqBJlyGTGB7bj4XLeYAdAnxa/Aj+HWwJcV2lLHlw0RFBTnY6cJH+pbSSEW9A=
    username: AgBUvUYs8T7WhZh/LElr+2Q640GFa/HaTZ7LmvoBqHnwC/urC+ICjkbbieBA4+057sOWoR8PZxkcTG9tfih/eOWgqopQPnTznEJgMxlSFJy7kwOEBJw8roRb9fo53ErID8pzIRQeAYnKV15yu2Z4o6IyzLryjeP97emS9VrBeaB7HSA5CW+FH8I/oJl6gdknZ5QWiBgTx+3RNc1u7pKNHXncseIYBiIG3R7LwpgRyjFitNQjnGwcUj9EbnqA1BdGMLEP8XG/aEnhUgBB1OBlaOHa3VXTgC/W+HowoW5oWLjht5Ea5e2iJh3F6VPRqMgvtABa3PdQPkaRHVrn+Skj30ABxg6QY8ZEceoIvb0gwXjMAS0kyS5PayhpGSZQHsm7rxctxB3LBJQEmH0WBppair7flpJdbDwoUdDXyfQys7e9PhZd+eJsZ910MqB8pgdQR1tT1VHW3EFLH0YLSvl2E+HIdJx2NUzfT0IIGq2R4IAyVKTE2DgEq075FWKXp3SddE9p+CVVIqdNevp3ZdTy7sGN59TYNruwV1+9DhHfIOtjUmB5pKcUwRDUmn3UISNuEa+KxJ+MEoyUkP4qD27EQpPIT6E3Nh3st/PDVS/fV+jd6xJzI/ufbRyICxB5OIv7MXDdZ30814TmzwYuZafuAPIxhoidSNEalruNympgSCYP1Sp3QsvypRBIwmZL6hFTcgheIZ1zfjZOKw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        cnpg.io/reload: "true"
      name: credentials-authelia
      namespace: postgresql-cluster
    type: kubernetes.io/basic-auth
