---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials-nocodb
  namespace: postgresql-cluster
spec:
  encryptedData:
    password: AgAbpR8y9hlq+jSHrPblxopchCJZ+vTuD5MHz9Nw9B+IeBCS5LuNCsJZ8Wem7x8KLzmmxqcSESvL0VX/hWberyz3rYsey0pFqB4OzAtx7L4KIqagCsEOwmGVrHV0ZDco+Fsgvw5KyVntfHyFAAATISOE6PrMjH66ZJAfwifJayLUzP3N0NK/lvtMtBQZf+JH+MTTcAjtQ8uQFj1RIkoxyAuXXkR0lr5Gm+HDuipQGt9p3SdqV25ufJ7Ywxn9fs/bxctL8dc+mopZTQNv6n0j4+4Zr0J3b7NFxrgo4XFkXr6Y6MUQKSAc4FLDdfknI9pb5i3lR5BFkGaM78eq76+ZmXajrHDvLz703d+ywBYJr6ZIF73FdYPXTrPLhskaNT1gHA4SfIRVJxy0qMOkeWOl+sI7LgkTqwHtL0MVBllWrq+4wTrpQtdmCCvLmDlfnAvO0DRRS4+2iwNLKxrr/JyKWMkhW3DkVPc69xBnM0eWPCNhYYbnE8beVwf3f1tyRqJ/G9s0DBbLg2NBeUWdTs5ZXHIaziK0VKks+cySKwPh0UXbB1Q0vNqdu1/gydMM2uk3m/PdnZUNFt8Sw7TCjim6wrNlrWJUsVIQRiYAQOWYVC857yKsYCluG1qwzTOFvWaO5fqAPJY8eZHTtEpzgr+ZXu2V7iFxpf94AShgbKufY/7Vmxivv4a7XZlBgpSByyqv8RW2okjSw44l/ZBhn2/fufL93q4pV8BkI8I/sgBBbrSyWQ==
    username: AgCdLyPj6Dxq5cjgxj3Urh0xWys64IRw9Fb5oVOhb/3ksHOkEc/ik2AOrinsJl9Q8qERRbmMeEL31sbDcMxjUmQdfFMh17rBhzrbfD042DeZj/rVj5TX86uJuQ9r8WWiP+braLEM6Cg7mCRwC7KYbngck7ePQycVigZ8WzKNmm0vzDl9Iq0XAbyLvScow4k3Vp5SJFGjMsOd17Y/OJqnZF53aTzNdmKcEaBF8Bz7jeWillPeD1lktz4rREVilZVirlmBBgSjuOLLHn/rcMFbVPOXwT3GHN129Llhgf1q2ZTc9YejL0ibNsPLJY0MwvCQ8/SDNWhu/VFEdoBF5qN+C/aDjmcTw3kT88fgHQc5KevHeBUwYDCRj5oKU7YJT4CX9BoAi+bxztygVbAq500vj2MWvGiY7V3nF+ntjOsX9mndT+6hqd/guxzHiFuLkMKNtNyJEEY4XEfRlrDtt3Kj2B/g42btUx2eWCmqh8zTRtpfQhy1A5q/r6h6rSDnC0XIBPRpmvSI7anZoFF70rxavSEhmJOIn+g1LNa3ObV+nA0P4hpoNSnZ3+v4NZBdRVAI+GjFysInbiuz8nyGgIiGewX+1s6yy0RwYSK3u3GKzlVzkxSTsGcV6BX1wh2+zMsFHb27W08CNANpdmLZkw/UTZKxSwI7nx6oRBSbLjwzsUw9L0y3JOnZSjHTpY5y/30wNO5GPFa4cho=
  template:
    metadata:
      creationTimestamp: null
      labels:
        cnpg.io/reload: "true"
      name: credentials-nocodb
      namespace: postgresql-cluster
    type: kubernetes.io/basic-auth
