apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-postgres-wal
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1Gi