apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-postgres-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi