apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-config
  namespace: youtrack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi