apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi # Should be several multiples of youtrack-data size