kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitea
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
      component: server
  template:
    metadata:
      labels:
        app: gitea
        component: server
    spec:
      containers:
        - name: gitea
          image: docker.io/gitea/gitea:latest
          env:
            - name: GITEA_APP_NAME
              value: Gitea | Constellation
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: gitea-postgres:5432
            - name: GITEA__database__NAME
              valueFrom:
                secretKeyRef:
                  name: gitea-postgres-credentials
                  key: database
            - name: GITEA__database__USER
              valueFrom:
                secretKeyRef:
                  name: gitea-postgres-credentials
                  key: username
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-postgres-credentials
                  key: password
          envFrom:
            - secretRef:
                name: gitea-env
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222
          volumeMounts:
            - name: config
              mountPath: /etc/gitea
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gitea-config
        - name: data
          persistentVolumeClaim:
              claimName: gitea-data