apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi